#!/usr/bin/env python3
"""Sync the Speakers page from the Sessionize SpeakerWall endpoint.

Downloads the headshot for every Accepted speaker into
`src/img/speakers/sessionize/` and regenerates `src/speakers/index.html`.

Re-run any time speakers change in Sessionize.

Manual overrides (keynote tag, workshop links, ordering) live in OVERRIDES below.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

SPEAKERWALL_URL = "https://sessionize.com/api/v2/e06bcrdo/view/SpeakerWall"

ROOT = Path(__file__).resolve().parents[1]
IMG_DIR = ROOT / "src" / "img" / "speakers" / "sessionize"
SPEAKERS_HTML = ROOT / "src" / "speakers" / "index.html"

USER_AGENT = "Mozilla/5.0 (compatible; eddd-speaker-sync)"

# Speakers already on the wall whose hand-tuned SCSS classes in main.scss
# should be reused instead of inline background-image. Keys are full names.
EXISTING_SCSS_CLASS = {
    "Eric Evans": "eric-evans",
    "Indu Alagarsamy": "indu-alagarsamy",
    "Paul Rayner": "paul-rayner",
    "Javiera Laso": "javiera-laso",
    "Sonya Natanzon": "sonya-natanzon",
    "Joseph Yoder": "joseph-yoder",
    "Tina Thomas": "tina-thomas",
    "Kyle Brown": "kyle-brown",
    "Chris Richardson": "chris-richardson",
    "Robert Sedor": "robert-sedor",
    "Jeremy Davis": "jeremy-davis",
}

# Curated annotations and ordering. Eric Evans is not in Sessionize; he is
# injected manually as the opening keynote.
ERIC_EVANS = {
    "fullName": "Eric Evans",
    "firstName": "Eric",
    "lastName": "Evans",
    "tagLine": "Author of Domain-Driven Design",
    "_role_html": "<strong>Opening Keynote</strong>",
    "_image_inline": False,
}

WORKSHOP_LINKS = {
    "Indu Alagarsamy": "/workshops/ai-assisted-architecture.html",
    "Paul Rayner": "/workshops/essential-ddd.html",
    "Chris Richardson": "/workshops/designing-microservices.html",
    "Matt Wynne": "/workshops/build-your-own-coding-agent.html",
    "Steven Diamante": "/workshops/build-your-own-coding-agent.html",
}

WORKSHOP_LEAD_ORDER = ["Indu Alagarsamy", "Paul Rayner", "Chris Richardson", "Matt Wynne", "Steven Diamante"]


def slugify(name: str) -> str:
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def fetch_speakerwall() -> list[dict]:
    req = urllib.request.Request(SPEAKERWALL_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def download_image(url: str, dest: Path) -> None:
    if dest.exists() and dest.stat().st_size > 0:
        return
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as r:
        dest.write_bytes(r.read())


def workshop_role_html(name: str) -> str | None:
    link = WORKSHOP_LINKS.get(name)
    if not link:
        return None
    return f'<strong><a href="{link}">Pre-Conference Workshop</a></strong>'


def speaker_card(s: dict) -> str:
    name = s["fullName"]
    tagline = s.get("tagLine", "").strip()
    role_html = s.get("_role_html") or workshop_role_html(name)

    css_class = EXISTING_SCSS_CLASS.get(name)
    if css_class:
        img_div = f'<div class="new-speaker-img {css_class}"></div>'
    else:
        slug = slugify(name)
        img_div = (
            f'<div class="new-speaker-img" '
            f'style="background-image: url(\'/img/speakers/sessionize/{slug}.jpg\'); '
            f'background-size: cover; background-position: center;"></div>'
        )

    parts = [
        '        <div class="speaker-container">',
        f'            {img_div}',
        f'            <p class="speaker-name">{name}</p>',
    ]
    if tagline:
        parts.append(f'            <p class="speaker-details">{tagline}</p>')
    if role_html:
        parts.append(f'            <p class="speaker-details">{role_html}</p>')
    parts.append('        </div>')
    return "\n".join(parts)


def order_speakers(api_speakers: list[dict]) -> list[dict]:
    by_name = {s["fullName"]: s for s in api_speakers}
    workshop_leads = [by_name[n] for n in WORKSHOP_LEAD_ORDER if n in by_name]
    rest = [s for s in api_speakers if s["fullName"] not in WORKSHOP_LEAD_ORDER]
    rest.sort(key=lambda s: (s.get("firstName", ""), s.get("lastName", "")))
    return [ERIC_EVANS] + workshop_leads + rest


def render_html(speakers: list[dict]) -> str:
    cards = "\n".join(speaker_card(s) for s in speakers)
    return f"""---
layout: layout-tier2.hbs
---

<!--
  Generated by scripts/sync-sessionize-speakers.py
  Re-run that script to refresh from the Sessionize SpeakerWall endpoint.
-->

<div class="container section speakers">
    <h1 class="text-center speakers-page-title">Speakers</h1>
    <div class="flex-row">
{cards}
    </div>
</div>
"""


def main() -> int:
    api = fetch_speakerwall()
    print(f"Fetched {len(api)} speakers from Sessionize")

    IMG_DIR.mkdir(parents=True, exist_ok=True)
    for s in api:
        if s["fullName"] in EXISTING_SCSS_CLASS:
            continue
        url = s.get("profilePicture")
        if not url:
            print(f"  ! no picture for {s['fullName']}")
            continue
        slug = slugify(s["fullName"])
        dest = IMG_DIR / f"{slug}.jpg"
        try:
            download_image(url, dest)
        except Exception as e:
            print(f"  ! failed to download {s['fullName']}: {e}")
            continue

    ordered = order_speakers(api)
    SPEAKERS_HTML.write_text(render_html(ordered))
    print(f"Wrote {SPEAKERS_HTML} with {len(ordered)} speakers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
